export enum ERRORS {
    E400 = "VALIDATION_ERROR",
    E404 = "NOT_FOUND",
    E409PLAN = "DUPLICATE_PLAN",
    E409VM = "VM_UNREMOVABLE",
    E500 = "INTERNAL_SERVER_ERROR",
    E401 = "INVALID_CREDENTIALS",
    E401U = "UNAUTHORIZED"
}